name: CD

on: push
# on:
#   push:
#     tags:
#       - "*"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install PNPM
        run: npm install -g pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile=false
      - name: Build and deploy
        run: pnpm run deploy
      - uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: public
          single-commit: true
          silent: true
          clean: true
