name: CI

on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install PNPM
        run: npm install -g pnpm
      - name: Install and test
        run: pnpm install-test --frozen-lockfile=false
